app/shop/models.py
import datetime

from app.ext import db


class Shop(db.Model):
    sid = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), index=True)
    price = db.Column(db.Numeric(10, 2))
    create_time = db.Column(db.DateTime, default=datetime.datetime.now())
    expiration_date = db.Column(db.String(64))
    status = db.Column(db.Integer)

app/__init__.py
from flask import Flask

from app.ext import init_ext, cache
from app.shop.views import shop
from app.upload.views import upload_blue

app = Flask(__name__)
app.debug = True


def create_app():
    init_ext(app=app)
    register_blue()
    return app


def register_blue():
    app.register_blueprint(shop, url_prefix='/shop')
    app.register_blueprint(cache, url_prefix='/cache')
    app.register_blueprint(upload_blue, url_prefix='/upload_blue')

app/cache01/views.py
from flask import Blueprint

from app.ext import cache

cache_blue = Blueprint('cache', __name__)

@cache.cached()
@cache_blue.route('/1/')
def cache_test1():
    print('天台见')
    return '1111'

app/shop/views.py
from flask import Blueprint, render_template, request, redirect

from app.ext import db
from .models import Shop

shop = Blueprint('shop', __name__)


@shop.route('/save/')
def save_all():
    objects = []
    for i in range(1, 101):
        objects.append(Shop(name='念旧' + str(i)))
    db.session.bulk_save_objects(objects)
    db.session.commit()
    return 'ok'


@shop.route('/limit/<int:page>/<int:size>/')
def query_limit(page, size):
    paginate = Shop.query.order_by(Shop.sid).paginate(page=page, per_page=size, error_out=False)
    shops = paginate.items
    return render_template('shop/index.html', shops=shops, paginate=paginate)


# @shop.route('/add/',methods=['POST'])
# def add_shop():
#     if request.method == 'GET':
#         pass
#     elif request.method == 'POST':
#         pass

# @shop.route('/search/<int:page>/<int:size>/', methods=['POST'])
# def search_shop(page, size):
#     content = request.form.get('content')
#     shops = Shop.query.filter(Shop.name.like('%' + content + '%'))
#     paginate = shops.query.order_by(Shop.sid).paginate(page=page, per_page=size, error_out=False)
#     shops = paginate.items
#     return render_template('shop/search.html', shops=shops, paginate=paginate)


@shop.route('/add/', methods=['get', 'post'])
def add_shop():
    if request.method == 'GET':
        sid = request.values.get('sid')
        shop = Shop.query.get(sid)
        return render_template('shop/add_shop.html', shop=shop)
    elif request.method == 'POST':
        name = request.values.get('name')
        price = request.values.get('price')
        expiration_date = request.values.get('expiration_date')
        status = request.values.get('status')
        shop = Shop(name=name,
                    price=price,
                    expiration_date=expiration_date,
                    status=status)
        db.session.add(shop)
        db.session.commit()
        return redirect('/shop/limit/1/10/')


@shop.route('/change/', methods=['get', 'post'])
def change_shop():
    if request.method == 'GET':
        sid = request.values.get('sid')
        shop = Shop.query.get(sid)
        return render_template('shop/change_shop.html', shop=shop)
    elif request.method == 'POST':
        sid = request.values.get('sid')
        name = request.values.get('name')
        price = request.values.get('price')
        expiration_date = request.values.get('expiration_date')
        status = request.values.get('status')
        Shop.query.filter(Shop.sid == sid).update({Shop.name: name,
                                                   Shop.price: price,
                                                   Shop.expiration_date: expiration_date,
                                                   Shop.status: status})
        db.session.commit()
        return redirect('/shop/limit/1/10/')

app/upload/views.py
from flask import Blueprint, request, render_template

from app.ext import images

upload_blue = Blueprint('upload', __name__)
'''
文件上传必须是post请求  form—data格式
'''
'''
UploadSet方法
1.save（）
参数：1.request.files（字典）
2.url
'''


@upload_blue.route('/img/', methods=['GET', 'POST'])
def upload_img():
    if request.method == 'POST':
        images.save(request.files['img'])
        return ''
    # 文件上传对象
    # request.files
    elif request.method == 'GET':
        return render_template('upload/upload.html')

app/templates/macro/macro.html
{% macro pagination(pagination,endpoint,size=10) %}

<ul>
    <li><a href="
    {% if pagination.has_prev %}
        {{ url_for(endpoint,page=pagination.page - 1,size=size) }}
    {% else %}
        #
    {% endif %}">上一页</a></li>
    {% for page in pagination.iter_pages(left_edge=9,right_edge=9) %}
        {% if page %}
            <li><a href="{{ url_for(endpoint,page=page, size=size) }}">{{ page }}</a></li>
        {% endif %}
    {% endfor %}
    <li><a href="
    {% if pagination.has_next %}
        {{ url_for(endpoint,page=pagination.page + 1,size=size) }}
    {% else %}
        #
    {% endif %}">下一页</a></li>
</ul>
{% endmacro %}

app/templates/shop/add_shop.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{{ url_for('shop.add_shop', sid=shop.sid) }}" method="post">
    <input type="hidden" name="sid" value="{{ shop.sid }}">
    <input type="text" name="name" value="{{ shop.name }}">商品名<br>
    <input type="text" name="price" value="{{ shop.price }}">商品价格<br>
    <input type="text" name="expiration_date" value="{{ shop.expiration_date }}">保质期<br>
    <input type="text" name="status" value="{{ shop.status }}">状态<br>
    <input type="submit" value="提交">
</form>
</body>
</html>

app/templates/shop/change_shop.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{{ url_for('shop.change_shop', sid=shop.sid) }}" method="post">
    <input type="hidden" name="sid" value="{{ shop.sid }}">
    <input type="text" name="name" value="{{ shop.name }}">商品名<br>
    <input type="text" name="price" value="{{ shop.price }}">商品价格<br>
    <input type="text" name="expiration_date" value="{{ shop.expiration_date }}">保质期<br>
    <input type="text" name="status" value="{{ shop.status }}">状态<br>
    <input type="submit" value="提交">
</form>
</body>
</html>

app/templates/shop/index.html
<!DOCTYPE html>
<html lang="en">
{% import 'macro/macro.html' as macro %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style type="text/css">
        table {
            width: 100%;
            border-collapse: collapse;
        }

        td, th {
            border: 1px solid blue;
            text-align: center;
        }

        ul {
            list-style: none;
            margin: 0px;
            padding: 0px;
        }

        ul li {
            float: left;
            margin: 10px;
        }

        ul a {
            text-decoration: none;
            font-size: 15px;
            cursor: pointer;
            color: black;
        }
    </style>
</head>
<body>
<table>
    <tr>
        <th>ID</th>
        <th>商品名</th>
        <th>价格</th>
        <th>注册时间</th>
        <th>保质期</th>
        <th>状态码</th>
        <th>选项</th>
    </tr>
    {% for shop in shops %}
        <tr>
            <td>{{ shop.sid }}</td>
            <td>{{ shop.name }}</td>
            <td>{{ shop.price }}</td>
            <td>{{ shop.create_time }}</td>
            <td>{{ shop.expiration_date }}</td>
            <td>{{ shop.status }}</td>
            <td>
                <a href="{{ url_for('shop.add_shop', sid=shop.sid) }}">添加</a>
                <a href="{{ url_for('shop.change_shop', sid=shop.sid) }}">修改</a>
                <a href="#">删除</a>
            </td>
            <td></td>
        </tr>
    {% endfor %}
</table>

{% if paginate %}
    <div>
        {{ macro.pagination(paginate,'shop.query_limit') }}
    </div>
{% endif %}
<div>
    <form action="#" method="post">
        <input type="text" name="content" placeholder="请输入商品名">
        <input type="submit" value="搜索">
    </form>
</div>
</body>
</html>

app/templates/shop/search.html
<!DOCTYPE html>
<html lang="en">
{% import 'macro.html' as macro %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<table>
    <tr>
        <th>ID</th>
        <th>商品名</th>
        <th>价格</th>
        <th>注册时间</th>
        <th>保质期</th>
        <th>状态码</th>
        <th>选项</th>
    </tr>
    {% for shop in shops %}
        <tr>
            <td>{{ shop.sid }}</td>
            <td>{{ shop.name }}</td>
            <td>{{ shop.price }}</td>
            <td>{{ shop.create_time }}</td>
            <td>{{ shop.expiration_date }}</td>
            <td>{{ shop.status }}</td>
            <td>
                <a href="#">添加</a>
                <a href="#">修改</a>
                <a href="#">删除</a>
            </td>
            <td></td>
        </tr>
    {% endfor %}
</table>

{% if paginate %}
    <div>
        {{ macro.pagination(paginate,'shop.query_limit') }}
    </div>
{% endif %}
<div>
    <form action="{{ url_for('shop.search_shop') }}" method="post">
        <input type="text" name="content" placeholder="请输入商品名">
        <input type="submit" value="搜索">
    </form>
</div>
</body>
</html>

app/templates/upload/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://cdn.bootcss.com/jquery/3.3.1/core.js"></script>
    <script type="text/javascript" language="JavaScript">
        $(function () {
            $('#upload_btn').click(function () {
                let formdata = new FormData($('#form')[0]);
                {#formdata.append('img', $('#image').files[0])#}
                let settings = {
                    url: 'http://127.0.0.1:9000/upload/img/',
                    type: 'post',
                    data: formdata,
                    //设置ajax不要缓存数据
                    cache: false,
                    //让jquery的ajax不要处理数据
                    processData: false,
                    //让jquery的ajax不要处理内容类型
                    contentType: false,
                    //回调函数
                    success: function (result) {
                        $('#wrap').append($('<img>')).attr('src', result.url)
                    }
                    error: function (status) {
                        alert(3145)
                    }
                    //无论请求成功或失败都会执行的函数
                    complete: function () {
                        alert(132154)
                    }
                };
                $.ajax(settings)
            })
        })

    </script>
</head>
<body>
<form id='form' action="{{ url_for('upload.upload_img') }}" method="post" enctype="multipart/form-data">
    <input type="file" id="image" name="img">
    <input type="button" id="upload_btn" value="sc">
</form>
<div id="wrap">

</div>
</body>
</html>